app:
  export-path: "Desktop/exports"
  date-format: "yyyy-MM-dd_HH-mm-ss"
  max-export-records: 10000

spring:
  application:
    name: studData

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/students_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:your_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

  security:
    user:
      name: admin
      password: admin

server:
  port: ${SERVER_PORT:8081}
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.example.studdata: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/studdata.log

---
spring:
  config:
    activate:
      on-profile: development
  jpa:
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false
  logging:
    level:
      com.example.studdata: WARN

management:
  endpoints:
    web:
      exposure:
        include: metrics,health,info,prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true